model:
  diffusion:
    latent_dim: 32
    hidden_dim: 768
    depth: 8
    heads: 12
    num_steps: 1000
    objective: "pred_noise"
    norm_type: layer
    dropout: 0
    cfg_scale: 7.0
    min_snr_loss_weight: False
    min_snr_gamma: 1
    # ckpt_path: /mnt/cluster/ssd6/zrs/sketechdream_log/logs/train_diff_20250702_230503/checkpoints/300000.pt
    ckpt_path: /root/autodl-fs-data3/gnndiff/logs/train_diff_20250821_223803/checkpoints/400000.pt

  vae:
    coord_dim: 3
    hidden_dim: 64
    latent_dim: 32
    norm_type: layer
    ckpt_path: /root/autodl-fs-data3/model/vae_1e-8_500k_32.pt

  clip:
    clip_embed_dim: 768
    ckpt_path: /root/autodl-fs-data3/model/clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41

val:
  data_mode: val
  use_random: true
  use_text: true
  seed: 2024
  batch_size: 5000
  num_workers: 32

dataset:
  name: node
  use_rotate: false
  clip_emb_root: /root/autodl-fs-data3/Articulation-XL2.0/clip_emb_caption
  val_file: /root/autodl-fs-data3/Articulation-XL2.0/test_meta.json

output_dir: /root/autodl-fs-data3/gnndiff/sample_compare/vis
skeleton_output_base_dir: /root/autodl-fs-data3/gnndiff/sample_compare/sample_sk